left_wheel_controller:
   type: "velocity_controllers/JointVelocityController"
   joint: "wheel_l_joint"

right_wheel_controller:
   type: "velocity_controllers/JointVelocityController"
   joint: "wheel_r_joint"

state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'wheel_l_joint'
    right_wheel: 'wheel_r_joint'
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
